- biliup/plugins/douyu.py
增加了一个参数判断是直播还是录播
https://www.douyu.com/wgapi/live/liveweb/getRoomLoopInfo?rid=房间号
如果vid不为空，则是录播状态，为空则属于直播或者未开播状态
> 现在能正确识别斗鱼是直播还是录播

- .gitignore
- biliup/engine/upload.py
如果文件夹名中含有 `index` 字符串的内容，则会在 `UploadBase` 类中的 `file_list` 函数错误地被判断为需上传和删除的文件，最终会因为 `os.remove` 函数无法删除文件夹导致出错。
此次在 `file_list` 函数中新增了一个确认条件以保证其返回值仅包含文件而不包含文件夹，同时为了方便使用 vscode 进行调试，在 `.gitignore` 中增加了 `.vscode` 行。
> fix bug & add .vscode in .gitignore

- biliup/plugins/bili_webup.py
当前biliup在登录时总是优先选择本地的持久化文件，即使在函数中提供了登录信息也不会去使用，感觉在将biliup作为库引用时这种逻辑有些不太合理，应当尽量优先使用login函数输入的登录信息，防止持久化文件中的token失效导致上传失败以及多账号切换。
> 修正bilibili登录信息优先级的问题

- biliup/plugins/huya.py
- biliup/plugins/twitch.py
- public/config.toml
- public/config.yaml
Updata twitch.py
Updata config.yaml
Updata config.toml
streamlink原文：https://streamlink.github.io/cli/plugins/twitch.html
> In addition to that, special API request headers can be set via [--twitch-api-header](https://streamlink.github.io/cli.html#cmdoption-twitch-api-header) or special API request parameters can be set via [--twitch-access-token-param](https://streamlink.github.io/cli.html#cmdoption-twitch-access-token-param) that can prevent ads from being embedded into the stream, either [authentication data](https://streamlink.github.io/cli/plugins/twitch.html#authentication) or other data discovered by the community.
> 添加对twitch的cookie支持，作用是可以不让广告嵌入到视频流中

- biliup/plugins/douyu.py
比如这个直播间 `https://www.douyu.com/265769`
导致其他的斗鱼直播都不能正常录制
> 修复斗鱼直播间被关闭一直报错的问题

- biliup/plugins/bilibili.py
- public/config.yaml
这下如果有写自定义Cookie又同时设置了第三方APi的情况下。如果打开了允许第三方API使用Cookie，那么就使用第三方API，如果没有允许（默认），那么设置的第三方APi就不生效，继续使用默认的API。
> 改进自定义API是否传Cookie的判断

- biliup/plugins/bilibili.py
- biliup/plugins/douyu.py
- biliup/plugins/huya.py
- biliup/plugins/kuaishou.py
- biliup/plugins/missevan.py
1. #421 改正日志等级
2. #437 尝试修复斗鱼，同时禁用主线路
> 斗鱼海外的主线路 `akm-h5` 会使用 `hls` 分片，同时卡顿丢帧严重，疑似回源问题（2023.05.18 测试时，日本 IP 已不再返回 主线路）
国内的主线路为斗鱼自建 `scdn`，类似于 `p2p`，有卡顿现象
综上，推荐使用其他 `cdn` 获得正常录制体验
3. #427 修正日志提示，尝试规避风控
> Some improvements

- biliup/engine/download.py
- biliup/plugins/huya.py
问题来源 在录制抖音的时候偶尔会获取直播流失败
测试中! 待验证是否成功
> 修复获取直播流失败后需要等delay触发

- biliup/plugins/bili_webup.py
- biliup/plugins/biliuprs.py
使用`@credit`占位,credits数组按顺序插入简介中,配置示例:
description = """
【{streamer}】{title}
@credit直播时间:%Y-%m-%d %H:%M:%S
@credit直播间地址：{url}
"""
#占位符数量不能少于credits中的的用户数
credits = [
{username="张三",uid=1234},
{username="李四",uid=1421421}
]
> bili_web上传插件新增简介@功能

- public/config.yaml
使用config.yaml中举例的credits配置会导致错误: KeyError: 'uid'
参考toml中正确的配置修改了config.yaml中credits的使用注释
> fix credits in config.yaml

- biliup/plugins/bili_webup.py
目前虽然提供了上传线路的选择，但传入`lines`参数的时候能选择的只是模式（`upos`, `kodo`, `cos`），即想选择UpOS模式下的线路（`bda2`, `qn`, `ws`）时不起作用，有可能的原因是在[preupload时只指定了模式却没有提及具体的线路](https://github.com/biliup/biliup/blob/41a8059785410ac09dbefb8c5a6e6783d4eede8e/biliup/plugins/bili_webup.py#L380C13-L391C27)
preupload结果提供的多个`endpoints`能说明在这几个CDN之间应该是能任意切换的
> 强制选择UpOS模式下的线路

- biliup/__main__.py
- biliup/database/db.py
- biliup/database/models.py
- biliup/engine/download.py
- biliup/engine/upload.py
- biliup/uploader.py
- 在数据库中增加一个表存储视频文件名，并通过外键与原下载信息表关联
- 在开始下载之前存储下载信息，保证在下载中断的情况下仍然可以获取直播标题、开播时间
> 在数据库中添加视频文件表

- biliup/config.py
- public/config.toml
- public/config.yaml
1. 当配置中不包含 tag 时抛出 KeyError
2. 在日语系统中默认 log 配置会在写入 log 时抛出 cp932 字符相关 Error
> 修复一些程序崩溃问题

- biliup/database/models.py
- biliup/uploader.py
修复了以下两个问题:
1.  持久化配置时丢失了streamer配置中的format项，录制内容始终为flv
2. streamer配置中没有uploader项时，uploader始终为None导致无法上传
> Fix: config配置持久化导致的丢失format、uploader获取异常问题

- app/dashboard/page.tsx
- app/ui/UserList.tsx
- app/upload-manager/edit/page.tsx
- biliup/handler.py
修复：
- 上传插件、简介艾特不能改回空值
- 空间配置分段大小单位错误
- 更改“正在下载中”日志等级为`DEBUG`
- 添加`cookies`文件路径填写提示
Fixes #795 , fixes #797
> Fix: 上传插件和简介艾特无法取消选择、分段大小单位错误

- biliup/handler.py
Fixes #787, fixes #750
批量检测时传入的`name`参数是`None`导致报错
> Fix: Twitch录制报错

- app/dashboard/page.tsx
- app/ui/TemplateFields.tsx
- ytb纵向分辨率类型错误
- 部分选项默认开启，webui中默认显示关闭
- 在前端添加限制：投稿标签不能为空，且不能超过12个，单个标签不能超过20字。符合b站投稿要求
Fixes #808
> 修复码率类型错误、部分选项默认开启、投稿标签添加限制

- biliup/database/models.py
- biliup/web/__init__.py
- pyproject.toml
Fix:
- 数据库记录转化为字典对象时`datetime`类型的值被过滤
- 新建空间配置时缺少`Session.commit()`，导致无法保存
> Fix: datetime被过滤、新建空间配置无法保存

- app/lib/use-streamers.ts
- biliup/__main__.py
- biliup/database/db.py
- biliup/engine/download.py
- biliup/handler.py
- biliup/web/__init__.py
- 增加几处显式释放连接
- 优化中间件关闭 Session
- 优化 `pre` 获取cookie文件方式
- 修复 WebUI 中cookie文件失效表现形式
> Fix: 超出连接池上限无法释放、webui中cookie文件显示错误

- app/streamers/page.tsx
修复：
直播间标题过长导致上方状态标识、下方按钮消失的问题；
部分浏览器页面宽度下，按钮溢出边框的问题。
调整：
将状态标识按钮调整为与旧版一致。
> 录播管理页面卡片样式优化

- .github/workflows/docker-publish.yml
- Dockerfile
- biliup/engine/download.py
- biliup/plugins/bilibili.py
- biliup/plugins/huya.py
- docker-compose.yml
原镜像: `899.11`MB → 新镜像: `614.13`MB
~~biliup 主程序不再为 `PID 1` 需求来自@Kataick~~ 没有了，待讨论
ffmpeg 切换为 `yt-dlp` 编译版，以支持 中国大陆平台的 `FLV_HEVC`
stream-gears 现在会遵循 时间分段/大小分段 提供的默认值
暂时移除 bili_cdn_fallback、bili_force_source、huya_cdn_fallback、bili原画链接复用，逻辑待重写
> 精简 Docker 镜像

- biliup/engine/download.py
- biliup/plugins/huya.py
- huya 变量名错误
- ffmpeg 正确匹配文件格式的 output format 以支持 mkv 和 ts 
- 文件名允许`・`（なかぐろ）和`°`
> 示例主播: https://space.bilibili.com/3546694188796294 https://space.bilibili.com/197098
> fix: val name err

- biliup/Danmaku/__init__.py
弹幕文件的xml适配B站格式，本地可以直接用[弹弹play](https://www.dandanplay.com/)直接播放弹幕版视频。
> feat: danmaku xml 兼容b站格式

- biliup/plugins/douyin.py
修复由[支持抖音短链录制弹幕](https://github.com/biliup/biliup/commit/56eb8d937b0e1b8a7305442280f9d4b3b3a2a228)造成的[错误](https://github.com/biliup/biliup/issues/1019#issuecomment-2272758013)
> 修复v0.4.75抖音默认开启录制弹幕的问题

- .eslintrc.json
- .prettierignore
- .prettierrc.toml
- .vscode/setting.json
- app/layout.tsx
- app/lib/utils/index.tsx
- app/ui/ThemeButton.tsx
- package-lock.json
- package.json
关于深色模式：
新增：
1、添加了「自动跟随系统主题」模式，并设置为默认行为，该模式将实时监控系统/浏览器主题，并同步变化；
2、添加了自动切换模式按钮。
修改：
1、修改按钮深色模式、浅色模式显示为对应当前模式；
2、修改默认主题为自动跟随系统。
关于代码格式化：
添加了eslint prettier vscodesetting 等格式化相关配置，用于解决 [【功能建议】给项目commit一个IDE的formatter配置吧 #736](https://github.com/biliup/biliup/issues/736) 的问题。
本次修改仅对前端代码生效，具体格式内容可在本次拉取请求中「.prettierrc.toml」文件中查看或修改。
为避免影响其他代码合并和复查，本次拉取请求并未对代码进行格式化，建议在项目根目录运行「npx prettier  --write ./**/*.tsx」格式化整个项目后，单独提交 commit。
⚠️由于 eslint 和 prettier 的格式化功能依赖部分 npm package ，本次添加对 package.json 等文件造成了更改！
> Feat(webui): 深色模式添加自动跟随系统，添加格式化配置文件。

- app/dashboard/page.tsx
- app/ui/plugins/bilibili.tsx
- app/ui/plugins/douyin.tsx
- app/ui/plugins/global.tsx
- app/ui/plugins/huya.tsx
- biliup/Danmaku/bilibili.py
- biliup/app.py
- biliup/engine/download.py
- biliup/handler.py
- biliup/plugins/bilibili.py
- biliup/plugins/douyin.py
- biliup/web/__init__.py
- public/config.toml
- public/config.yaml
- `bili_ov2cn`: 将海外CDN域名替换为大陆CDN域名。
- `bili_anonymous_origin`: 免登录录制`hls_fmp4`原画。
- `bili_hls_transcode_timeout`: `hls_fmp4`转码超时时间。
- `douyin_double_screen`: 控制抖音双屏直播录制方式。resolves #1100
- `webui(录播管理)`: 校验相似录播备注。resolves #1086
- `bili_perfCDN`: 更名为`bili_cdn`，以匹配其他平台选项名称。
- `webui(哔哩哔哩)`: 调整部分选项位置。
- `plugin`: 减少无用日志输出。
- `bili_force_source`: 修复因`sk`参数过长导致的验证失败。
- `douyin`: fixes #1105 部分抖音用户 sec_user_id 更新至 76 位。
- `bili_protocol`: 因`哔哩哔哩APP(粉版/大陆版/大陆商店版)`已移除对`hls_ts`的支持，跟进官方处理。
> feat: enhance dashboard and plugin

- biliup/Danmaku/__init__.py
参考弹幕p部分的参数兼容 bilibili 主站弹幕 XML 文件，按顺序含义分别为：
1.弹幕出现时间 (秒)
2.弹幕类型
3.字号
4.颜色
5.发送时间戳
6.固定为 0 (主站弹幕 XML 为弹幕池 ID)
7.发送者 UID (主站弹幕 XML 为发送用户 ID 的 CRC32)
8.固定为 0 (主站弹幕 XML 为弹幕的数据库 ID)
同时修改发送者昵称为user，以兼容DanmakuFactory可识别用户名
> B站弹幕部分的参数兼容DanmakuFactory可识别用户名

- biliup/__init__.py
- biliup/common/util.py
- pyproject.toml
- 提升 Python Version 依赖到 >= 3.9
- 更新依赖版本
- 缓解由 aiohttp 新版引入的[问题](https://github.com/aio-libs/aiohttp/issues/10519)
- 在 Python >=3.10 时默认信任系统证书，其他版本默认使用 certifi
> Update dependencies and Python version requirements

- biliup/__init__.py
- biliup/engine/download.py
- biliup/plugins/twitch.py
回归下载器选择streamlink时的正常行为，否则其实twitch那两个streamlink的参数实际上是下载器在ffmpeg时候才能用到的，不过感觉这么写好丑……
另一个想法是给streamlink下载加个参数然后全局下载器命令接受这些参数作为输入，可能也更方便提供一些插件的自定义？
顺便看了下，nico也是给的streamlink参数然后流式输出到本地http，感觉会有跟twitch那边之前一样的问题？不过我跑半天nico直播也没跑起来一直403。
> fix: 回归下载器选择streamlink时的正常行为

- biliup/plugins/stream_gears.py
fix #1214, fix #1204, fix #1161
#1193 应该也是这个问题
steam_gears.upload新加入了topic_id参数，但biliup中没有，多个参数没有对应上。
这会导致用户手动上传投稿失败，日志如下：
```
2025-04-02 23:30:53,039 uploader.py[line:64](Pid:1 Tname:Thread-13 (biliup_uploader)) ERROR Uncaught exception:
Traceback (most recent call last):
File "/biliup/biliup/uploader.py", line 62, in biliup_uploader
return cls(index, data, **kwargs).upload(filelist)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/biliup/biliup/plugins/stream_gears.py", line 78, in upload
stream_gears.upload(
TypeError: argument 'copyright': 'str' object cannot be interpreted as an integer
```
> fix: stream-gears上传投稿参数错误

- biliup/__init__.py
- biliup/common/util.py
- biliup/engine/download.py
- biliup/plugins/__init__.py
- biliup/plugins/bilibili.py
- biliup/plugins/biliuprs.py
- biliup/plugins/douyin.py
- biliup/plugins/huya.py
- biliup/plugins/stream_gears.py
- pyproject.toml
- 解决：全局应用`huya_mobile_api`. Resolves #1227 
- 修复：未设定`bili_cookies`时，错误抛出`nav err`. Fixes #1231 
- 修复：程序无法调用`ffmpeg`时，回退`stream-gears`以防止卡死WEB进程.
- 优化：调整`httpx`超时时间.
- 添加 `{platform}`. #1163 
- 标题允许 `\u3001` 和 `\u3002` #1203
> refactor: plugins.Huya

- README.md
```md
1. 确保 Node.js 版本 ≥ 18
2. 安装依赖：`npm i`
3. 启动开发服务器：`npm run dev`
4. 启动 Biliup：`python3 -m biliup`
5. 访问：`http://localhost:3000`
```
按原先步骤描述安装到第四步时，会缺少 python 项目的相关依赖包；安装依赖启动后缺少 public 目录，启动报错；可新建一个 public 或者执行 `npm run build` 将静态资源打一份到后台
> docs: 修复开发环境缺失的步骤

- package-lock.json
- package.json
sass build 时作用，将 sass 编译为 css，不需要作为生产依赖
ncp 拷贝文件，同理。
> fix: ncp and sass should not production dependencies

- app/ui/plugins/huya.tsx
- biliup/__init__.py
- biliup/engine/download.py
- biliup/plugins/huya.py
- Fixes #1272
- Fixes #1274 
- Fixes #1288 
- Fixes #1275 
- Fixes #1290
> fix(Plugins.Huya): Update HuYaUA

- biliup/engine/download.py
可能修复了极少数情况下使用sync-downloader上传时，稿件标题为直播间标题和简介未格式化的情况。
> 可能修复了边录边传稿件标题为直播间标题和简介未格式化的情况

- biliup/plugins/huya.py
当直播标题带有`&amp;`(&)等转义字符时，现阶段会提前结束正则匹配，导致无法检测状态。
> fix(Plugins.Huya): 修复当标题存在转义字符时正则匹配失败的问题

- biliup/Danmaku/bilibili.py
2025-05-27B站`api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo`接口需要携带WBI信息, 简单修复了一下, 测试修改后可以正常录制B站弹幕, 可能需要review一下, 不太熟悉Python, 不知道wbi在设计的时候有没有考虑在plugin包之外使用.
> fix(Danmaku.bilibili): 修复B站弹幕连接异常

- .vscode/setting.json
- biliup/engine/download.py
解决因 https://github.com/biliup/biliup/commit/9c95762e78735127473f539576a9f83c1cf6338a 
导致的Windows下无法保存文件以及 https://github.com/biliup/biliup/issues/1320
和 https://github.com/biliup/biliup/issues/1324
中的BUG
> fix: 回滚文件名编解码返回逻辑以修复直接出现 unicode 的问题

- biliup/plugins/ttinglive.py
解决[#1421](https://github.com/biliup/biliup/issues/1421)
> Flextv由原地址 https://www.flextv.co.k 更改为 https://www.ttinglive.com

- biliup/engine/upload.py
- biliup/handler.py
fix: 修复下播延迟检测期间文件名改动导致上传错误KeyError, 在延迟检测后重新获取上传文件以回归之前版本的行为
v1.0.1之前: 下播延迟检测结束 -> upload()内部会重新获取上传文件列表 -> 延迟检测期间改动过但符合主播命名规则文件可以被正常上传投稿(未restart的情况下投稿的title时间等信息正常保留)
v1.0.1加入上传重试次数限制后: 下播延迟检测结束 -> upload()前get_max_upload_count()检测文件上传次数(但未更新文件列表) -> 延迟检测期间的改动造成KeyError -> 上传错误 -> 再次等待下播延迟检测后重新上传 -> 因为文件名变动丢失投稿title时间等信息(即使在未restart的情况下)
refine: get_max_upload_count() 次数统计不再包含运行目录下无关的所有文件和目录
> fix(upload): fix glitches in max_upload_limit

- crates/biliup-cli/migrations/2_fix_preprocessor_null.sql
修复由于历史更新造成的一些需要Json的字段被字符串被"null"填充问题
> Fix null/"null" values in JSON fields for livestreamers tables
