biliup/biliup

biliup/engine/download.py
biliup/plugins/acfun.py
biliup/plugins/bilibili.py
biliup/plugins/douyu.py
biliup/plugins/egame.py
biliup/plugins/huya.py

录像文件包含当前直播间标题，支持斗鱼、虎牙、AcFun、Bilibili、企鹅电竞。

录像文件包含直播间标题

---

biliup/plugins/bili_webup.py

set chunk_size is 10M

---

biliup/plugins/douyin.py

Add  Douyin Mainpage Url Support For Douyin Recorder

---

biliup/plugins/youtube.py

支持以下链接
- https://www.youtube.com/channel/xxx/live
- https://www.youtube.com/playlist?list=xxx
- https://www.youtube.com/watch?v=xxx

Added {title} support to Youtube plugin

---

biliup/plugins/bili_webup.py

目前即便指定了上传路线，依旧会进行probe
`upload_file(filepath="path/to/file.mp4", lines="kodo")`

如果指定了上传线路将不再进行probe

---

biliup/plugins/huya.py

Updata huya.py 修复虎牙获取不到标题的BUG

---

public/config.yaml

修复config.yaml配置格式

---

public/config.yaml

优化config.yaml的布局，将配置分为了4个板块，完善了一些描述

---

biliup/plugins/twitch.py
public/config.toml
public/config.yaml

修复twitch_cookie配置不生效问题

---

biliup/plugins/bilibili.py

1. #295 尝试换用更为安全的写法
2. #300 尝试为无效链接启用 Fallback

Try to fix #295 , #300

---

biliup/engine/download.py
biliup/engine/upload.py
biliup/plugins/bilibili.py
public/config.toml
public/config.yaml

在最后处理文件的时候，自动删除多余的xml弹幕文件，只保留有同样文件名视频的弹幕xml文件
新增streamlink+ffmpeg混合下载器选项
新增B站直播hls_fmp4流的获取（目前只有streamlink+ffmpeg混合模式才能稳定下载）

一系列feature

---

.gitignore
biliup/engine/download.py
biliup/plugins/bilibili.py
biliup/plugins/douyu.py
public/config.toml
public/config.yaml

1. 优化部分逻辑
2. 新增跳过斗鱼scdn
3. 修复配置文件错误

Optimize the plugin code of Douyu and Bilibili

---

CHANGELOG.md
biliup/__init__.py
biliup/engine/download.py
biliup/plugins/youtube.py
public/config.toml
public/config.yaml

[优化streamlink下载参数](https://github.com/biliup/biliup/commit/2c8272e0e79c0b5c0fbd1ff8604bd8341b1eea98)
[支持YouTube下载指定日期范围内的视频](https://github.com/biliup/biliup/commit/71288eedccd9da71731fe20e9e8f54d9e6f48331)

支持YouTube下载指定日期范围内的视频与一系列优化

---

biliup/plugins/kuaishou.py

[Feature] Added support for Kuaishou.

---

biliup/plugins/bilibili.py
public/config.toml
public/config.yaml

* Increase timeout to 60s as 45s is too short in some cases

bilibili: Longer fmp4 timeout

---

biliup/plugins/huya.py

Revert "修复虎牙可能导致进程终止问题"

---

biliup/engine/download.py
biliup/plugins/twitch.py
public/config.toml
public/config.yaml

增加Twitch的去广告开关（解决广告分段问题）
修改当请求流错误时等待delay的值的合理性，写死为30秒（防止有人等待的太久）
增加、修正toml，yaml文件的配置和注释

增加Twitch的去广告开关（解决广告分段问题）

---

biliup/downloader.py
biliup/plugins/nico.py

NICO标题获取从BS4改为正则，开播后仍然重复请求的BUG的修复

NICO标题获取从BS4改为正则，开播后仍然重复请求的BUG的修复

---

biliup/handler.py

Revert "preprocessor增加开播时返回主播名字和开播地址"

---

biliup/engine/download.py

修复(#504)触发后不重新录制的问题

---

biliup/plugins/biliuprs.py

https://github.com/biliup/biliup-rs/pull/96

修复biliup-rs的参数绑定

---

biliup/plugins/kuaishou.py

https://github.com/biliup/biliup/issues/515#issuecomment-1636671683

修正快手 HLS 流原画

---

public/config.toml
public/config.yaml

对简介@功能(#518)补充config

---

biliup/__main__.py
biliup/common/tools.py
biliup/downloader.py
biliup/engine/download.py
biliup/engine/upload.py
biliup/handler.py
biliup/plugins/noop_uploader.py
biliup/plugins/youtube.py
public/config.toml
public/config.yaml

youtube添加单独下载直播和回放选项
youtube添加streams playlists shorts类型链接支持
youtube添加筛选无效时提示
youtube配置说明修改
youtube不会在运行目录产生多余文件了
将上传录像时可以开始新的录制调整为默认功能
封面下载支持webp
下载上传逻辑调整
启动时删除临时缓存文件

youtube添加功能 调整上传下载逻辑

---

biliup/plugins/bilibili.py
public/config.toml
public/config.yaml

优化bilibili提示报错

---

biliup/plugins/bilibili.py

#676 添加登录验证，原画链接复用
使用移动端房间信息，获取正确 emoji 标题

优化 BiliLive 部分运行逻辑

---

biliup/plugins/bilibili.py

#668 6cf4f4ee2cc4b590c9e2517e26726d353e5401e6
#676

Fix variable names

---

.gitignore
biliup/plugins/bilibili.py
public/config.toml
public/config.yaml

Read cookies from the file by biliup-rs to log in to Bililive

---

biliup/engine/download.py

自动修正stream_gears设置不支持的format

---

biliup/database/db.py

Fix: 标题为空时下载报错

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/ISSUE_TEMPLATE/feature-request.yaml

Feat: 添加issue模板

---

.env.production
app/dashboard/page.tsx
app/ui/TemplateFields.tsx
app/upload-manager/edit/page.tsx
biliup/app.py
biliup/config.py
biliup/database/db.py
biliup/web/__init__.py

- 新建录播管理报错
- 空间配置无法加载初始值
- 空间配置部分样式
- 投稿管理部分字段不对应
- 不开始任务 #725 
- 更新录播管理时若选择投稿模板报错
- webui中只能选择`cookie.json`文件对应的用户
- API SERVER固定为`http://localhost:19159`
-----------------
测试用安装包:
[biliup-fix-20231231-1.zip](https://github.com/biliup/biliup/files/13801208/biliup-fix-20231231-1.zip)

尝试修复webui一些bug

---

app/ui/TemplateFields.tsx
app/upload-manager/edit/page.tsx
biliup/config.py
biliup/web/__init__.py

- 空间配置无法更新
- 修改投稿模板时报错
- 投稿模板中用户字段不对应
- 已配置投稿模板不显示
- webui中只能选择cookie.json文件对应的用户
- API SERVER固定为http://localhost:19159
- 刷新时404
--------------
- ~[biliup-fix-20240101-1.zip](https://github.com/biliup/biliup/files/13803858/biliup-fix-20240101-1.zip)~
- [biliup-fix-20240101-2.zip](https://github.com/biliup/biliup/files/13803966/biliup-fix-20240101-2.zip)

尝试修复一些WebUI的Bug

---

app/upload-manager/edit/page.tsx
biliup/handler.py
biliup/uploader.py

- 分区为空时，打开`upload-manager/edit`页面报错
- title为空时，上传报错
- 将"无需上传"日志级别改为`Debug`
- 刷新404
- 只能选择cookie.json
- 删除streamer后下载不停止
---------------------
- [biliup-0.4.32a1.tar.gz](https://github.com/biliup/biliup/files/13807920/biliup-0.4.32a1.tar.gz)

尝试修复webui的一些bug

---

.gitignore
package-lock.json

webui 主要开发者的 lock 文件如果与我的冲突，请优先使用主要开发者的 lock 文件。

commit lock 文件，保证开发者使用相同的npm依赖版本

---

app/dashboard/page.tsx
app/lib/api-streamer.ts
app/ui/TemplateFields.tsx
app/ui/TemplateModal.tsx
app/upload-manager/add/page.tsx
app/upload-manager/edit/page.tsx
biliup/config.py
biliup/database/db.py
biliup/database/models.py
biliup/handler.py

- 最简配置无法上传
- 上传结束不自动删除
- “更多设置”折叠后配置丢失
- 空间配置downloader、submit_api字段、用户cookie相关字段
- 录制配置format、前后处理等
- 上传配置credits
- 配置项按平台分组并折叠
----------------------
- [biliup-0.4.32a2.tar.gz](https://github.com/biliup/biliup/files/13850639/biliup-0.4.32a2.tar.gz)

Webui 20240104

---

app/lib/api-streamer.ts
app/streamers/page.tsx
app/ui/TemplateModal.tsx
app/upload-manager/page.tsx

- 在接收、发送时处理postprocess的值，完全适配旧版配置文件：#765 
- 用户列表为空时阻止新建投稿模板,并弹出提示：#756

适配postprocess返回值格式

---

biliup/plugins/bilibili.py
biliup/plugins/missevan.py

对随机ua的一些补充

---

app/dashboard/page.tsx
app/lib/api-streamer.ts
app/lib/use-streamers.ts
app/ui/TemplateFields.tsx
app/upload-manager/add/page.tsx
app/upload-manager/edit/page.tsx

添加：
- 自定义封面
- b站录播优选CDN
修复：
- 账号列表头像显示问题
Fixes #759, fixes #754

添加 webui 缺失的配置项，修复账号信息显示问题

---

app/dashboard/page.tsx

修复webui的某些输入框类型问题

---

app/dashboard/page.tsx
app/layout.tsx
app/page.tsx
app/styles/dashboard.module.scss

主要改动：
优化了「空间配置」页的外观，并修正了部分有可能导致歧义的文字表述；
重新排版了部分交互项；
更改了部分交互的类型，如：部分填写项修改为选择项，部分输入框修改为密码框；
其他：
将HTML语言标志由「en」更改为「zh-Hans」。
（为了满足强迫症）导航页面添加了「Home」选项卡，并修改文字为60px的「Hello, Welcome to biliup!」。 
（为了满足强迫症）格式化并整理了部分代码。

Fix: refined the webui.

---

biliup/__main__.py
biliup/web/__init__.py

- 添加--no-access-log参数，使webui不输出访问日志
- 修改webui启动提示

添加--no-access-log参数、修改webui启动提示

---

app/dashboard/page.tsx
app/styles/dashboard.module.scss
app/ui/plugins/bilibili.tsx
app/ui/plugins/cookie.tsx
app/ui/plugins/developer.tsx
app/ui/plugins/douyin.tsx
app/ui/plugins/douyu.tsx
app/ui/plugins/global.tsx
app/ui/plugins/huya.tsx
app/ui/plugins/twitch.tsx
app/ui/plugins/youtube.tsx

主要修改：
拆分各平台配置项代码为单个组件，方便后续维护；
修改了部分文字表述，并优化文字排版，使其更易于理解；
优化部分文字显示以及排版；
修复部分功能默认开启，但前端显示为关闭的BUG。
新增：
添加开发者选项，可用于控制日志输出等级。

UI代码组件化，修复部分选项BUG，文字表述优化，新增日志配置项。

---

biliup/__main__.py
biliup/config.py
biliup/database/db.py
biliup/database/migration/env.py
biliup/database/migration/script.py.mako
biliup/database/models.py
biliup/web/__init__.py
pyproject.toml

Refactoring database using sqlalchemy

---

app/dashboard/page.tsx
app/layout.tsx
app/page.module.css
app/streamers/page.tsx
app/ui/plugins/cookie.tsx
biliup/engine/download.py
biliup/plugins/bilibili.py
biliup/plugins/huya.py
biliup/plugins/kuaishou.py

- 修复: `WebUI` 侧栏控制按钮样式错误
- 修复: `WebUI` 空间配置 `Collapse` 块宽度错误
- 修复: `Huya` 标题丢失
- 修复: `302目标链接` 日志打印时机错误
- 移除: `Bililive` 登录态校验失败时移除 `Cookie`

[Fix] Style errors and missing Title

---

.gitignore
biliup/plugins/douyin.py
biliup/plugins/huya.py

Add more log

---

app/streamers/page.tsx

删除原有样式，并替换组件为Card，以修复录播管理页卡片重叠问题。

修复录播管理页卡片重叠问题

---

app/streamers/page.tsx
app/ui/plugins/developer.tsx

修复因缺失 handlers 参数而导致日志格式丢失，以及无法获取DEBUG以外等级日志的问题。
原理：OnChange属性中调用api添加参数，若之前受到过此bug影响，可尝试切换至其他日志等级。保存后将自动修复。

Fix：日志格式以及丢失问题

---

biliup/plugins/youtube.py

- 修复Youtube在记录已下载视频或直播时意外错误(无需担心因为此错误导致重复下载)
- 让Youtube配置项在使用配置文件时针对单个录制配置时生效(原有全局配置可在单个录制下设置)

修复Youtube在下载完成前的意外错误

---

biliup/plugins/huya.py

避免虎牙在选取码率时发生错误后依旧继续执行

---

.gitignore
app/dashboard/page.tsx
app/ui/plugins/douyu.tsx
app/ui/plugins/global.tsx
app/ui/plugins/huya.tsx
app/ui/plugins/twitcasting.tsx
app/ui/plugins/twitch.tsx
biliup/engine/download.py
biliup/plugins/Danmaku/__init__.py
biliup/plugins/Danmaku/bilibili.py
biliup/plugins/Danmaku/douyin.py
biliup/plugins/Danmaku/douyu.py
biliup/plugins/Danmaku/huya.py
biliup/plugins/Danmaku/twitcasting.py
biliup/plugins/Danmaku/twitch.py
biliup/plugins/twitcasting.py
public/config.toml
public/config.yaml

适配 Twitcasting.TV

---

biliup/__init__.py
biliup/engine/download.py
biliup/handler.py
package-lock.json
package.json

新增分段后处理功能(返回当前分段的视频文件 只支持run指令)

---

.gitignore
biliup/engine/download.py
biliup/plugins/bilibili.py
biliup/plugins/huya.py
biliup/plugins/twitch.py

粗略测试中发现 Twitch 一个请求最高同时查询 35 个用户

限制 Twitch 同时查询数量

---

app/ui/plugins/douyu.tsx
biliup/plugins/douyu.py
biliup/plugins/huya.py

测试直播: `https://www.douyu.com/11265503`

feat(Douyu): 拒绝互动游戏

---

biliup/__main__.py
biliup/config.py
biliup/engine/download.py
biliup/plugins/huya.py

在参数为 `stop` 或 `--version` 时，不再创建 `data` 文件夹
#961

Minimal import

---

biliup.spec
biliup/__init__.py
biliup/__main__.py
biliup/database/db.py
biliup/plugins/bilibili.py
pyproject.toml

| 事件情况  | 旧版      | 新版      |
|---------|-----------|-----------|
| `no_http`，非首次运行，存在配置文件 | 备份，创建新数据库 | 备份，创建新数据库 | 完成
| `no_http`，非首次运行，没有配置文件 | 备份，创建新数据库 | _**不更新数据库**_ | 完成
| `no_http`，首次运行，存在配置文件 | 创建新数据库，导入 | 创建新数据库，导入 | 完成
| `no_http`，首次运行，没有配置文件 | 创建数据库 | 创建数据库 | 完成
| 非首次运行，存在配置文件 | 不更新数据库 | 不更新数据库 | 完成
| 非首次运行，没有配置文件 | 不更新数据库 | 不更新数据库 | 完成
| 首次运行，存在配置文件 | 创建新数据库，导入 | 创建新数据库，导入 | 完成
| 首次运行，没有配置文件 | 创建数据库 | 创建数据库 | 完成

fix: first run error

---

biliup/plugins/douyu.py

减少douyu通过发送请求获取房间号次数

---

biliup/engine/download.py
biliup/plugins/bilibili.py
biliup/plugins/douyin.py

resolve #1008 #1004 
多屏直播测试: `https://live.douyin.com/848632609874`
电台直播测试: `https://live.douyin.com/914996270765`

适配抖音短链、电台、多屏直播

---

biliup/Danmaku/douyin.py
biliup/Danmaku/douyu.py
biliup/__init__.py
biliup/plugins/douyin.py
biliup/plugins/douyu.py
biliup/plugins/huya.py

支持抖音短链录制弹幕

---

app/history/page.tsx
app/job/page.tsx

fix(webui): 修复直播历史与历史记录排序问题

---

.github/workflows/docker-publish.yml
Dockerfile
app/history/page.tsx
app/job/page.tsx

flx(build): 修复#1025 npm会编译失败的问题

---

biliup/engine/download.py
biliup/plugins/huya.py

fix(Huya): platform_id error

---

biliup/database/db.py
biliup/handler.py
biliup/plugins/douyin.py
biliup/uploader.py

Fix(Upload): 重传时未能从数据库获取直播信息

---

app/layout.tsx
app/streamers/page.tsx
app/ui/QRcode.tsx
app/upload-manager/page.tsx
next.config.js

- 修改之前
- /streamers
- /upload-manager
- 修改之后
- /streamers
- /upload-manager

style: refactor mobile client header style

---

biliup/common/util.py
biliup/plugins/huya.py

fix(huya): skip query param generation for "xingxiu" streamers

---

app/ui/plugins/bilibili.tsx
biliup/Danmaku/__init__.py
biliup/Danmaku/bilibili.py
biliup/plugins/bilibili.py

新增功能：
1.录制的弹幕文件中保存用户UID、用户昵称、系统时间戳
2.新增支持醒目留言、礼物、大航海信息的录制

feat: B站弹幕录制优化

---

biliup/Danmaku/bilibili.py
biliup/plugins/bilibili.py

修改内容：
1.B站弹幕认证Uid从CookieFile中获得（多线程实在不是很会，就用曲线救国的方案了）
2.区分表情包和普通弹幕

perf: 优化B站弹幕录制

---

app/dashboard/page.tsx
app/history/page.tsx
app/job/Filter.tsx
app/job/page.tsx
app/layout.tsx
app/lib/utils/index.tsx
app/page.tsx
app/status/page.tsx
app/streamers/page.tsx
app/ui/AvatarCard/index.tsx
app/ui/Player.tsx
app/ui/QRcode.tsx
app/ui/TemplateFields.tsx
app/ui/TemplateModal.tsx
app/ui/UserList.tsx
app/ui/plugins/bilibili.tsx
app/ui/plugins/cc.tsx
app/ui/plugins/cookie.tsx
app/ui/plugins/developer.tsx
app/ui/plugins/douyin.tsx
app/ui/plugins/douyu.tsx
app/ui/plugins/global.tsx
app/ui/plugins/huya.tsx
app/ui/plugins/twitcasting.tsx
app/ui/plugins/twitch.tsx
app/ui/plugins/youtube.tsx
app/upload-manager/add/page.tsx
app/upload-manager/edit/page.tsx
app/upload-manager/page.tsx

Style(webui): 执行前端代码格式化

---

app/dashboard/page.tsx
app/ui/plugins/global.tsx
app/ui/plugins/kilakila.tsx
biliup/plugins/kilakila.py

Integrated Kilakila plugin into the dashboard streaming platforms section.
Resolves #1147

feat: Add Kilakila streaming platform support

---

app/dashboard/page.tsx
app/lib/api-streamer.ts
app/streamers/page.tsx
app/ui/OverrideModal.tsx
app/ui/TemplateFields.tsx
app/ui/TemplateModal.tsx
app/ui/plugins/bilibili.tsx
app/ui/plugins/cc.tsx
app/ui/plugins/douyin.tsx
app/ui/plugins/douyu.tsx
app/ui/plugins/huya.tsx
app/ui/plugins/index.ts
app/ui/plugins/kilakila.tsx
app/ui/plugins/twitcasting.tsx
app/ui/plugins/twitch.tsx
app/ui/plugins/youtube.tsx
biliup/database/models.py
biliup/downloader.py
biliup/engine/download.py
biliup/plugins/bilibili.py
biliup/plugins/cc.py
biliup/plugins/douyin.py
biliup/plugins/douyu.py
biliup/plugins/huya.py
biliup/plugins/kilakila.py
biliup/plugins/twitch.py

新增 单个用户配置覆写全局配置
修复 `Bililive` 获取不到低清晰度
resolves #1142
resolves #1138
<details open>
<summary>Test it</summary>
> This requires Git to be installed on your system.
```shell
pip install --upgrade --force-reinstall git+https://github.com/xxxxuanran/biliup.git@override-streamer
```
</details>

feat: Add override configuration support for streamers

---

biliup/common/util.py

feat: Use system certificate store by default

---

.gitignore
biliup/__init__.py
biliup/engine/download.py
biliup/plugins/huya.py
public/config.toml
public/config.yaml

- 更新 User-Agent 以解决 虎牙星秀区下载失败。( Resolves #1196 )
- 不再下载虎牙回放

fix(Huya): 星秀区下载错误

---

biliup/plugins/twitch.py

https://github.com/streamlink/streamlink/pull/5704

fix: 移除streamlink的弃用参数

---

app/ui/plugins/bilibili.tsx
biliup/Danmaku/__init__.py
biliup/Danmaku/bilibili.py
biliup/plugins/bilibili.py
public/config.toml
public/config.yaml

feat: 支持B站完整弹幕录制

---

app/lib/api-streamer.ts
app/ui/OverrideModal.tsx
app/ui/TemplateModal.tsx
biliup/app.py
biliup/database/models.py
biliup/engine/download.py
biliup/plugins/douyin.py
biliup/plugins/kilakila.py
biliup/plugins/kuaishou.py
biliup/plugins/youtube.py
public/config.toml
public/config.yaml

每次检查时，如果room_title 包含关键词不录制 #1195

feature: 关键词不录播

---

biliup/Danmaku/__init__.py

修改原始弹幕录制逻辑。目前的逻辑是弹幕类型为弹幕文本或礼物则不会写入原始弹幕，个人认为原始弹幕是从B站服务器接受到什么数据就写入什么数据

mod: 修改原始弹幕录制逻辑

---

biliup/__init__.py
biliup/engine/sync_downloader.py
biliup/plugins/__init__.py
biliup/plugins/bilibili.py

- Added Wbi class for handling WBI key updates and signing requests.
- Integrated WBI signing into Bililive class for room info retrieval.
- Introduced methods to extract keys from URLs and manage WBI key updates based on timestamps.
- Fixes #1222

feat: Implement WBI signing mechanism for Bilibili API requests

---

Dockerfile

- 在Dockerfile中添加了`curl`依赖，并手动标记`wget`和`curl`为手动安装
fixed: #1259

chore(Dockerfile): 更新Dockerfile配置

---

app/ui/plugins/douyin.tsx
biliup/__init__.py
biliup/plugins/douyin.py

- 开启`douyin_true_origin`后，不再录制重编码为AVC的原画流。未测试电台、聊天室等直播间。

feat: 抖音真原画

---

biliup/__init__.py
biliup/plugins/huya.py

fix(huya): update ua ts calculation and mobile api key error

---

biliup/plugins/biliuprs.py
biliup/uploader.py

fix: 修复播完自动上传时，仅自己可见状态失效

---

app/ui/plugins/twitcasting.tsx
biliup/__init__.py
biliup/plugins/twitcasting.py

feat: 适配TwitCasting,TwitCasting添加Cookie,TwitCasting添加画质选择

---

Dockerfile

全局声明C.UTF-8以修正中文等字符的表现，解决 https://github.com/biliup/biliup/issues/1332 的问题

fix(Docker): 声明字符编码以解决乱码问题

---

app/ui/plugins/bilibili.tsx
biliup/engine/download.py
biliup/plugins/bilibili.py
biliup/plugins/biliuprs.py

- 默认录制`原画真彩`画质，以替代`强制真原画`功能
- 修复 #1394 引入的错误 fixes #1401 
- fixes #1323

fix(blive): parse error

---

crates/biliup/src/uploader/bilibili.rs
crates/biliup/src/uploader/credential.rs

Exactly the same as https://github.com/biliup/biliup-rs/pull/225

Fix(bilibili-rs): Usu https instead of http

---

.gitignore
biliup/plugins/__init__.py
biliup/plugins/douyu.py

- 去除对 JSEngine 的强依赖。现在没有安装任何 JS 解释器也可以录制斗鱼直播。
- 修复上次重构时，错误添加的 `iar=1` 导致默认设置下非最高画质问题。
- 为 `VipRoom` 使用请求新请求接口 `playweb.douyucdn.cn`。该接口可以正确请求 `hs-h5` cdn。
- 优化 `hs-h5` 构建逻辑。
- 添加自动重试。Fixes #1376

refactor(Douyu): 去除对 JSEngine 的强依赖

---

biliup/common/abogus.py
biliup/plugins/douyin.py
pyproject.toml

特别感谢 [Johnserf-Seed/f2](https://github.com/Johnserf-Seed/f2) 开源 `a_bogus` 算法
- 添加 [纯 Python 运行的 `a_bogus`](https://github.com/Johnserf-Seed/f2/blob/main/f2/utils/abogus.py) 计算方法。
- 补充 可能缺失的 `cookie` 参数。方法来自 [hua0512/rust-srec](https://github.com/hua0512/rust-srec)。
Fixed #1450
Fixed #1444

fix(Douyin): add abogus
